# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 16:57
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Sum
from django.db.models.functions import Coalesce


def init_last_weeks_hours(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    for project in Project.objects.all():
        last_week_hours = project.categories.aggregate(sum=Coalesce(Sum('items__actual'), 0))
        project.last_weeks_hours = last_week_hours['sum']
        project.save()


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_last_weeks_hours)
    ]
