# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 15:27
from __future__ import unicode_literals

from django.db import migrations
from projects.models import Project


def init_last_weeks_hours(apps, schema_editor):

    for project in Project.objects.all():
        project.last_weeks_hours = project.actual
        project.save()

class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_last_weeks_hours)
    ]

