# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 15:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171027_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='previous_weeks_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), blank=True, default=list, size=None),
        ),
    ]
