# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170828_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='actual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='estimated',
            field=models.IntegerField(),
        ),
    ]
