# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170829_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='buffer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
