# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170831_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='actual',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='estimated',
            field=models.FloatField(),
        ),
    ]
