# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20170907_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='actual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='estimated',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
