# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170908_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_weeks_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
