# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20171026_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_imported_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
