# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 19:00
from __future__ import unicode_literals

from django.db import migrations
from projects.models import Project


def init_last_weeks_hours(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    for project in Project.objects.all():
        project.last_weeks_hours = project.actual
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_last_imported_date'),
    ]

    operations = [
        migrations.RunPython(init_last_weeks_hours)
    ]
