# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 20:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20171103_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_weeks_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='previous_weeks_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False), blank=True, default=list, size=None),
        ),
    ]
