# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20171001_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='harvest_tokens_last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
