# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 13:38
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_expires_at',
            field=models.DateTimeField(default=authentication.models.fourteen_days_ahead),
        ),
    ]
