# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_harvest_tokens_last_refreshed_at'),
        ('authentication', '0003_userprofile_beta'),
    ]

    operations = [
    ]
