# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_20171002_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='harvest_tokens_last_refreshed_at',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
