# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sent'), (2, 'Accepted')]),
        ),
    ]
