# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20170906_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='invitations.Invitation', verbose_name='invitation'),
        ),
    ]
