# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20170908_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='trial_expires_at',
            field=models.DateTimeField(default=teams.models.fourteen_days_ahead),
        ),
    ]
